{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "056776da",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The autoreload extension is already loaded. To reload it, use:\n",
      "  %reload_ext autoreload\n"
     ]
    }
   ],
   "source": [
    "%load_ext autoreload\n",
    "%autoreload 2"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "13ca001b",
   "metadata": {},
   "source": [
    "import the notebook's functions and init connection with database."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "ae032fba",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[32m2025-08-18 21:32:13.111\u001b[0m | \u001b[1mINFO    \u001b[0m | \u001b[36msrc.services.db.database\u001b[0m:\u001b[36minit_alchemy_engine\u001b[0m:\u001b[36m31\u001b[0m - \u001b[1mStarting service..\u001b[0m\n",
      "\u001b[32m2025-08-18 21:32:13.113\u001b[0m | \u001b[41m\u001b[1mCRITICAL\u001b[0m | \u001b[36msrc.core.utils\u001b[0m:\u001b[36mload_env_var\u001b[0m:\u001b[36m87\u001b[0m - \u001b[41m\u001b[1mCannot load env var named 'RUNNING_INSIDE_DOCKER'. returning None.\u001b[0m\n",
      "\u001b[32m2025-08-18 21:32:13.123\u001b[0m | \u001b[34m\u001b[1mDEBUG   \u001b[0m | \u001b[36msrc.services.db.database\u001b[0m:\u001b[36minit_alchemy_engine\u001b[0m:\u001b[36m42\u001b[0m - \u001b[34m\u001b[1mpostgresql+asyncpg://user:pwd@localhost:5432/EyeMath_db\u001b[0m\n",
      "\u001b[32m2025-08-18 21:32:13.143\u001b[0m | \u001b[1mINFO    \u001b[0m | \u001b[36msrc.services.db.database\u001b[0m:\u001b[36minit_alchemy_engine\u001b[0m:\u001b[36m61\u001b[0m - \u001b[1m\u001b[32mConnection with data base has been established!\u001b[0m\n"
     ]
    }
   ],
   "source": [
    "from src.notebooks.data.example_data import *\n",
    "\n",
    "await data_base.init_alchemy_engine()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2a053ac0",
   "metadata": {},
   "source": [
    "Generating test data for the database."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "8a78a5f0",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[32m2025-08-18 21:32:14.436\u001b[0m | \u001b[1mINFO    \u001b[0m | \u001b[36msrc.notebooks.data.example_data\u001b[0m:\u001b[36mseed_data\u001b[0m:\u001b[36m5\u001b[0m - \u001b[1mSeeding 325 users...\u001b[0m\n",
      "\u001b[32m2025-08-18 21:32:14.436\u001b[0m | \u001b[31m\u001b[1mERROR   \u001b[0m | \u001b[36msrc.notebooks.data.example_data\u001b[0m:\u001b[36mseed_data\u001b[0m:\u001b[36m89\u001b[0m - \u001b[31m\u001b[1mError seeding data\u001b[0m\n",
      "\u001b[33m\u001b[1mTraceback (most recent call last):\u001b[0m\n",
      "\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/home/usov/myprojects/books_store/db_manager/.venv/lib/python3.13/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "    │   └ <bound method Application.launch_instance of <class 'ipykernel.kernelapp.IPKernelApp'>>\n",
      "    └ <module 'ipykernel.kernelapp' from '/home/usov/myprojects/books_store/db_manager/.venv/lib/python3.13/site-packages/ipykernel...\n",
      "  File \"/home/usov/myprojects/books_store/db_manager/.venv/lib/python3.13/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "    │   └ <function IPKernelApp.start at 0x7aaeb5348900>\n",
      "    └ <ipykernel.kernelapp.IPKernelApp object at 0x7aaeb54e56a0>\n",
      "  File \"/home/usov/myprojects/books_store/db_manager/.venv/lib/python3.13/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "    │    │       └ <function BaseAsyncIOLoop.start at 0x7aaeb53499e0>\n",
      "    │    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7aaeb54e7a10>\n",
      "    └ <ipykernel.kernelapp.IPKernelApp object at 0x7aaeb54e56a0>\n",
      "  File \"/home/usov/myprojects/books_store/db_manager/.venv/lib/python3.13/site-packages/tornado/platform/asyncio.py\", line 211, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "    │    │            └ <function BaseEventLoop.run_forever at 0x7aaeb6be8680>\n",
      "    │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>\n",
      "    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7aaeb54e7a10>\n",
      "  File \"/home/usov/.local/share/uv/python/cpython-3.13.5-linux-x86_64-gnu/lib/python3.13/asyncio/base_events.py\", line 683, in run_forever\n",
      "    self._run_once()\n",
      "    │    └ <function BaseEventLoop._run_once at 0x7aaeb6bea480>\n",
      "    └ <_UnixSelectorEventLoop running=True closed=False debug=False>\n",
      "  File \"/home/usov/.local/share/uv/python/cpython-3.13.5-linux-x86_64-gnu/lib/python3.13/asyncio/base_events.py\", line 2042, in _run_once\n",
      "    handle._run()\n",
      "    │      └ <function Handle._run at 0x7aaeb6b6bf60>\n",
      "    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x7aae81dcc190>()>\n",
      "  File \"/home/usov/.local/share/uv/python/cpython-3.13.5-linux-x86_64-gnu/lib/python3.13/asyncio/events.py\", line 89, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "    │    │            │    │           │    └ <member '_args' of 'Handle' objects>\n",
      "    │    │            │    │           └ <Handle <_asyncio.TaskStepMethWrapper object at 0x7aae81dcc190>()>\n",
      "    │    │            │    └ <member '_callback' of 'Handle' objects>\n",
      "    │    │            └ <Handle <_asyncio.TaskStepMethWrapper object at 0x7aae81dcc190>()>\n",
      "    │    └ <member '_context' of 'Handle' objects>\n",
      "    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x7aae81dcc190>()>\n",
      "  File \"/home/usov/myprojects/books_store/db_manager/.venv/lib/python3.13/site-packages/IPython/core/interactiveshell.py\", line 3394, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "                       │    │             │        │     └ '/tmp/ipykernel_452522/2494168068.py'\n",
      "                       │    │             │        └ [<ast.Expr object at 0x7aae815f0e90>]\n",
      "                       │    │             └ <ast.Module object at 0x7aae815f1190>\n",
      "                       │    └ <function InteractiveShell.run_ast_nodes at 0x7aaeb60e9300>\n",
      "                       └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x7aaeb41b8c20>\n",
      "  File \"/home/usov/myprojects/books_store/db_manager/.venv/lib/python3.13/site-packages/IPython/core/interactiveshell.py\", line 3639, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "             │    │        │     │              └ True\n",
      "             │    │        │     └ <ExecutionResult object at 7aae965f1d90, execution_count=26 error_before_exec=None error_in_exec=None info=<ExecutionInfo obj...\n",
      "             │    │        └ <code object <module> at 0x7aae81797830, file \"/tmp/ipykernel_452522/2494168068.py\", line 1>\n",
      "             │    └ <function InteractiveShell.run_code at 0x7aaeb60e93a0>\n",
      "             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x7aaeb41b8c20>\n",
      "  File \"/home/usov/myprojects/books_store/db_manager/.venv/lib/python3.13/site-packages/IPython/core/interactiveshell.py\", line 3697, in run_code\n",
      "    await eval(code_obj, self.user_global_ns, self.user_ns)\n",
      "               │         │    │               │    └ <property object at 0x7aaeb60d8590>\n",
      "               │         │    │               └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x7aaeb41b8c20>\n",
      "               │         │    └ <property object at 0x7aaeb60d85e0>\n",
      "               │         └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x7aaeb41b8c20>\n",
      "               └ <code object <module> at 0x7aae81797830, file \"/tmp/ipykernel_452522/2494168068.py\", line 1>\n",
      "\n",
      "  File \"\u001b[32m/tmp/ipykernel_452522/\u001b[0m\u001b[32m\u001b[1m2494168068.py\u001b[0m\", line \u001b[33m1\u001b[0m, in \u001b[35m<module>\u001b[0m\n",
      "    \u001b[35m\u001b[1mawait\u001b[0m \u001b[1mseed_data\u001b[0m\u001b[1m(\u001b[0m\u001b[1m)\u001b[0m\n",
      "    \u001b[36m      └ \u001b[0m\u001b[36m\u001b[1m<function seed_data at 0x7aae962fbba0>\u001b[0m\n",
      "\n",
      "> File \"<string>\", line 12, in seed_data\n",
      "  File \"<string>\", line 4, in __init__\n",
      "  File \"/home/usov/myprojects/books_store/db_manager/.venv/lib/python3.13/site-packages/sqlalchemy/orm/state.py\", line 571, in _initialize_instance\n",
      "    with util.safe_reraise():\n",
      "         │    └ <class 'sqlalchemy.util.langhelpers.safe_reraise'>\n",
      "         └ <module 'sqlalchemy.util' from '/home/usov/myprojects/books_store/db_manager/.venv/lib/python3.13/site-packages/sqlalchemy/ut...\n",
      "  File \"/home/usov/myprojects/books_store/db_manager/.venv/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py\", line 224, in __exit__\n",
      "    raise exc_value.with_traceback(exc_tb)\n",
      "          │         │              └ <traceback object at 0x7aae815f2580>\n",
      "          │         └ <method 'with_traceback' of 'BaseException' objects>\n",
      "          └ AttributeError(\"'NoneType' object has no attribute 'set'\")\n",
      "  File \"/home/usov/myprojects/books_store/db_manager/.venv/lib/python3.13/site-packages/sqlalchemy/orm/state.py\", line 569, in _initialize_instance\n",
      "    manager.original_init(*mixed[1:], **kwargs)\n",
      "    │       │              │            └ {'user_name': 'user_0', 'hashed_password': 'Password123!', 'first_name': 'Андрей', 'last_name': 'Николаев', 'middle_name': 'Р...\n",
      "    │       │              └ (<sqlalchemy.orm.state.InstanceState object at 0x7aae81537ad0>, <bs_models.user.User object at 0x7aae81567cf0>)\n",
      "    │       └ <function _declarative_constructor at 0x7aae965407c0>\n",
      "    └ <ClassManager of <class 'bs_models.user.User'> at 7aae96451040>\n",
      "  File \"/home/usov/myprojects/books_store/db_manager/.venv/lib/python3.13/site-packages/sqlalchemy/orm/decl_base.py\", line 2176, in _declarative_constructor\n",
      "    setattr(self, k, kwargs[k])\n",
      "            │     │  │      └ 'user_name'\n",
      "            │     │  └ {'user_name': 'user_0', 'hashed_password': 'Password123!', 'first_name': 'Андрей', 'last_name': 'Николаев', 'middle_name': 'Р...\n",
      "            │     └ 'user_name'\n",
      "            └ <bs_models.user.User object at 0x7aae81567cf0>\n",
      "  File \"/home/usov/myprojects/books_store/db_manager/.venv/lib/python3.13/site-packages/sqlalchemy/orm/attributes.py\", line 537, in __set__\n",
      "    self.impl.set(\n",
      "    │    └ <member 'impl' of 'QueryableAttribute' objects>\n",
      "    └ <sqlalchemy.orm.attributes.InstrumentedAttribute object at 0x7aae820c4220>\n",
      "\n",
      "\u001b[31m\u001b[1mAttributeError\u001b[0m:\u001b[1m 'NoneType' object has no attribute 'set'\u001b[0m\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "'NoneType' object has no attribute 'set'",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mAttributeError\u001b[39m                            Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[26]\u001b[39m\u001b[32m, line 1\u001b[39m\n\u001b[32m----> \u001b[39m\u001b[32m1\u001b[39m \u001b[38;5;28;01mawait\u001b[39;00m seed_data()\n",
      "\u001b[36mFile \u001b[39m\u001b[32m<string>:12\u001b[39m, in \u001b[36mseed_data\u001b[39m\u001b[34m()\u001b[39m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m<string>:4\u001b[39m, in \u001b[36m__init__\u001b[39m\u001b[34m(self, **kwargs)\u001b[39m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/myprojects/books_store/db_manager/.venv/lib/python3.13/site-packages/sqlalchemy/orm/state.py:571\u001b[39m, in \u001b[36mInstanceState._initialize_instance\u001b[39m\u001b[34m(*mixed, **kwargs)\u001b[39m\n\u001b[32m    569\u001b[39m     manager.original_init(*mixed[\u001b[32m1\u001b[39m:], **kwargs)\n\u001b[32m    570\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m571\u001b[39m \u001b[43m    \u001b[49m\u001b[38;5;28;43;01mwith\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43mutil\u001b[49m\u001b[43m.\u001b[49m\u001b[43msafe_reraise\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[43m:\u001b[49m\n\u001b[32m    572\u001b[39m \u001b[43m        \u001b[49m\u001b[43mmanager\u001b[49m\u001b[43m.\u001b[49m\u001b[43mdispatch\u001b[49m\u001b[43m.\u001b[49m\u001b[43minit_failure\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/myprojects/books_store/db_manager/.venv/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py:224\u001b[39m, in \u001b[36msafe_reraise.__exit__\u001b[39m\u001b[34m(self, type_, value, traceback)\u001b[39m\n\u001b[32m    222\u001b[39m     \u001b[38;5;28;01massert\u001b[39;00m exc_value \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[32m    223\u001b[39m     \u001b[38;5;28mself\u001b[39m._exc_info = \u001b[38;5;28;01mNone\u001b[39;00m  \u001b[38;5;66;03m# remove potential circular references\u001b[39;00m\n\u001b[32m--> \u001b[39m\u001b[32m224\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m exc_value.with_traceback(exc_tb)\n\u001b[32m    225\u001b[39m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[32m    226\u001b[39m     \u001b[38;5;28mself\u001b[39m._exc_info = \u001b[38;5;28;01mNone\u001b[39;00m  \u001b[38;5;66;03m# remove potential circular references\u001b[39;00m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/myprojects/books_store/db_manager/.venv/lib/python3.13/site-packages/sqlalchemy/orm/state.py:569\u001b[39m, in \u001b[36mInstanceState._initialize_instance\u001b[39m\u001b[34m(*mixed, **kwargs)\u001b[39m\n\u001b[32m    566\u001b[39m manager.dispatch.init(\u001b[38;5;28mself\u001b[39m, args, kwargs)\n\u001b[32m    568\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m569\u001b[39m     \u001b[43mmanager\u001b[49m\u001b[43m.\u001b[49m\u001b[43moriginal_init\u001b[49m\u001b[43m(\u001b[49m\u001b[43m*\u001b[49m\u001b[43mmixed\u001b[49m\u001b[43m[\u001b[49m\u001b[32;43m1\u001b[39;49m\u001b[43m:\u001b[49m\u001b[43m]\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    570\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m:\n\u001b[32m    571\u001b[39m     \u001b[38;5;28;01mwith\u001b[39;00m util.safe_reraise():\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/myprojects/books_store/db_manager/.venv/lib/python3.13/site-packages/sqlalchemy/orm/decl_base.py:2176\u001b[39m, in \u001b[36m_declarative_constructor\u001b[39m\u001b[34m(self, **kwargs)\u001b[39m\n\u001b[32m   2172\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28mhasattr\u001b[39m(cls_, k):\n\u001b[32m   2173\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mTypeError\u001b[39;00m(\n\u001b[32m   2174\u001b[39m         \u001b[33m\"\u001b[39m\u001b[38;5;132;01m%r\u001b[39;00m\u001b[33m is an invalid keyword argument for \u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[33m\"\u001b[39m % (k, cls_.\u001b[34m__name__\u001b[39m)\n\u001b[32m   2175\u001b[39m     )\n\u001b[32m-> \u001b[39m\u001b[32m2176\u001b[39m \u001b[38;5;28;43msetattr\u001b[39;49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mk\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mkwargs\u001b[49m\u001b[43m[\u001b[49m\u001b[43mk\u001b[49m\u001b[43m]\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/myprojects/books_store/db_manager/.venv/lib/python3.13/site-packages/sqlalchemy/orm/attributes.py:537\u001b[39m, in \u001b[36mInstrumentedAttribute.__set__\u001b[39m\u001b[34m(self, instance, value)\u001b[39m\n\u001b[32m    536\u001b[39m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34m__set__\u001b[39m(\u001b[38;5;28mself\u001b[39m, instance: \u001b[38;5;28mobject\u001b[39m, value: Any) -> \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m537\u001b[39m     \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43mimpl\u001b[49m\u001b[43m.\u001b[49m\u001b[43mset\u001b[49m(\n\u001b[32m    538\u001b[39m         instance_state(instance), instance_dict(instance), value, \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[32m    539\u001b[39m     )\n",
      "\u001b[31mAttributeError\u001b[39m: 'NoneType' object has no attribute 'set'"
     ]
    }
   ],
   "source": [
    "await seed_data()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
